# 1) Load the data
import the load_digits function from the sklearn.datasets library

invoke load_digits with the return_X_y parameter set to true and store the returned dataset in variable X and y.

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import  classification_report, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score


import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import random as rnd

In [2]:
# Load  dataset
from sklearn.datasets import load_digits
digits_X, digits_y = load_digits(return_X_y=True)

In [3]:
digits_y

array([0, 1, 2, ..., 8, 9, 8])

In [4]:
# split the datasets into training and test data
digits_X_train, digits_X_test, digits_y_train, digits_y_test = train_test_split(digits_X, digits_y)

# 2) Perform a few exploratory steps including:

Display the number of rows of data returned

Display the number of features in the dataset

Use Numpy's bincount to display how many samples belong to each class. Is this a balanced dataset?

In [5]:
import numpy as n
print('The number of rows in the dataset is {:d}'.format(digits_X.shape[0]))
print('The number of features in the dataset is {:d}'.format(digits_X.shape[1]))

# balancing is about target variable.
np.bincount(digits_y)


# x are the features and is target variable

The number of rows in the dataset is 1797
The number of features in the dataset is 64


array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180])

In [6]:
# displays how many 0s, 1s, 2s,.,.

## Prepare training and testing data
1. Use *train_test_split* to split the dataset into a training set and a test set. Set the proportion of test data to 20%. Set a random state value so that the results will be repeatable.

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits_X, digits_y, test_size=.20, random_state=50)


# Cross validation with Logistic Regression
In this step you will create a LogisticRegression classifier and use 5-fold cross validation to train the model.

import LogisticRegression classifier from sklearn

instantiate a LogisticRegression classifier with the 'lbfgs' solver and 'ovr' multiclass strategy. You may have to 

set the maximum number of iterations to 1000.

perform cross validation on the model

print the cross validation scores and the mean of the cross validation scores.

In [8]:
# Using ovr
digits_ovr_lr_clf = LogisticRegression(solver='lbfgs', multi_class='ovr',  max_iter=1000)
digits_ovr_lr_clf.fit(digits_X_train, digits_y_train)
digits_ovr_proba = digits_ovr_lr_clf.predict_proba(digits_X_test)

# we see the first instance
digits_ovr_proba[0:1]

array([[1.24481151e-16, 9.99704409e-01, 1.34856486e-06, 4.37011649e-08,
        3.86070962e-07, 1.51188947e-09, 1.69733488e-11, 7.72850575e-06,
        2.86082673e-04, 5.50473070e-13]])

In [9]:
# using multiclass
digits_multinomial_lr_clf = LogisticRegression(solver='lbfgs', multi_class='multinomial',  max_iter=10000)
digits_multinomial_lr_clf.fit(digits_X_train, digits_y_train)
digits_multinomial_proba = digits_multinomial_lr_clf.predict_proba(digits_X_test)

# we see the first instance
digits_multinomial_proba[0:1]

array([[3.12852205e-13, 9.99932313e-01, 9.15479762e-07, 1.89416015e-07,
        3.36051798e-07, 3.27200830e-11, 5.89494328e-10, 1.36128541e-05,
        5.26326922e-05, 2.51357241e-10]])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(digits_X, digits_y, random_state=40)
clf = LogisticRegression(solver='lbfgs')
cv_scores = cross_val_score(clf, X_train, y_train, cv = 5)

print('Accuracy scores for the 5 folds: ', cv_scores)
print('Mean cross validatiion score: {:.3f}'.format(np.mean(cv_scores)))

/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:94

Accuracy scores for the 5 folds:  [0.95238095 0.93333333 0.94795539 0.95167286 0.94736842]
Mean cross validatiion score: 0.947


/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to 

# Cross validation with RandomForest
Perform the same steps as above but this time with a RandomForestClassifier.

In [26]:
rf_clf = RandomForestClassifier(n_estimators=24, random_state = 40 )
rf_cv_scores = cross_val_score(clf, digits_X, digits_y, cv = 5)

print('Accuracy scores for the 5 folds: ', cv_scores)
print('Mean cross validation score: {:.3f}'.format(np.mean(rf_cv_scores)))


/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:94

/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:94

Accuracy scores for the 5 folds:  [0.95238095 0.93333333 0.94795539 0.95167286 0.94736842]
Mean cross validation score: 0.921


/Users/kingcheneyon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
